//! HTML wrappers for exported calculation summaries.

use super::markdown_render::markdown_to_html_fragment;

const CLINSIZE_HTML_STYLES: &str = r#"
    :root {
      color-scheme: light;
    }
    body {
      font-family: "IBM Plex Sans", Calibri, Arial, sans-serif;
      color: #14171c;
      background: #f5f6f8;
      margin: 0;
      padding: 2.5rem 1.5rem;
      line-height: 1.55;
      font-size: 10.5pt;
    }
    .page {
      max-width: 46rem;
      margin: 0 auto;
      padding: 2rem 2.25rem;
      background: #ffffff;
      border: 1px solid #d9dee6;
      border-radius: 12px;
      box-shadow: 0 1px 2px rgba(20, 23, 28, 0.06);
    }
    .doc-header {
      margin-bottom: 1.5rem;
      padding-bottom: 1rem;
      border-bottom: 1px solid #d9dee6;
    }
    .doc-kicker {
      margin: 0 0 0.35rem;
      font-size: 0.6875rem;
      font-weight: 600;
      letter-spacing: 0.06em;
      text-transform: uppercase;
      color: #3b5bdb;
    }
    .doc-title {
      margin: 0;
      font-family: Georgia, "Times New Roman", serif;
      font-size: 1.75rem;
      font-weight: 600;
      color: #14171c;
    }
    h1 {
      font-family: Georgia, "Times New Roman", serif;
      font-size: 1.5rem;
      font-weight: 600;
      color: #14171c;
      margin: 0 0 1rem;
    }
    h2 {
      font-size: 0.8125rem;
      font-weight: 700;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      color: #3b5bdb;
      margin: 1.75rem 0 0.65rem;
    }
    p {
      margin: 0.35rem 0;
    }
    ul {
      margin: 0.35rem 0 0.75rem;
      padding-left: 1.25rem;
    }
    li {
      margin: 0.3rem 0;
    }
    strong {
      font-weight: 600;
    }
    .doc-footer {
      margin-top: 2rem;
      padding-top: 0.85rem;
      border-top: 1px solid #d9dee6;
      font-size: 0.75rem;
      color: #5b6470;
      text-align: center;
    }
    @media print {
      body {
        background: #ffffff;
        padding: 0;
      }
      .page {
        border: none;
        box-shadow: none;
        max-width: none;
        padding: 0;
      }
    }
"#;

/// Wrap a Markdown calculation summary in a printable HTML document.
pub fn markdown_to_html_document(markdown: &str, title: &str) -> String {
    let body = markdown_to_html_fragment(markdown);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>{CLINSIZE_HTML_STYLES}</style>
</head>
<body>
  <main class="page">
    <header class="doc-header">
      <p class="doc-kicker">ClinSize calculation summary</p>
      <h1 class="doc-title">{title}</h1>
    </header>
    {body}
    <footer class="doc-footer">Generated by ClinSize</footer>
  </main>
</body>
</html>"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn html_document_includes_title_and_rendered_markdown() {
        let html = markdown_to_html_document(
            "# ClinSize calculation summary\n\n## Method\n\n- **Method:** Two-sample t-test\n",
            "Two-sample t-test",
        );
        assert!(html.contains("<title>Two-sample t-test</title>"));
        assert!(html.contains("doc-title"));
        assert!(html.contains("<h2>Method</h2>"));
        assert!(html.contains("<strong>Method:</strong>"));
        assert!(!html.contains("**Method:**"));
    }
}
